const CH1 = {
        "To smear something with": "Enduire",
        "To throw something at / to hurl something at": "Lancer quelque chose",
        "A painting": "Une peinture",
        "Paint": "De la peinture",
        "To make themselves heard": "Pour se faire entendre",
        "To make somebody aware of / to raise awareness": "Faire prendre conscience de",
        "To draw attention": "Attirer l'attention",
        "Demonstrators": "Manifestants",
        "To splash, to splatter something across": "Balancer",
        "Coffin": "Cercueil",
        "To cross": "Traverser",
        "Neither, nor": "Ni, ni",
        "To snore": "Ronfler",
        "Snoring": "Ronflement",
        "Puffy/swollen": "Bouffi",
        "Grown-up": "Grande personne",
        "To claim": "Réclamer",
        "Distraught": "Désespéré",
        "Game (hunting)": "Gibier",
        "Game-bag": "Carnier",
        "Cartridge": "Cartouche",
        "So as not to / in order not to": "Pour ne pas",
        "To refill/fill in": "Remplir",
        "Pale/dim": "Pâle",
        "Dawn": "Aube",
        "Blink/flicker": "Clignoter",
        "Shutter": "Volet",
        "To nail": "Clouer",
        "Bottle": "Biberon",
        "To outweigh / to be heavier": "Peser plus lourd",
        "Lack of": "Manquer de",
        "Further / to promote": "Promouvoir",
        "Sparked": "Déclenché",
        "Unless": "À moins que",
        "Timeless": "Intemporel",
        "Demonstration": "Manifestation",
        "Hold somebody accountable": "Tenir quelqu’un responsable",
        "Live on handouts": "Vivre des aides",
        "Western": "Occidental",
        "Wipe off": "Enlever",
        "To be unemployed": "Être au chômage",
        "Widespread": "Généralisé",
        "Harm somebody": "Nuire à quelqu’un",
        "Stunt": "Un coup de pub",
        "Slack": "Fainéant",
        "Sew": "Coudre",
        "To delay": "Reporter",
        "To summarize": "Résumer",
        "To resume": "Reprendre",
        "A summary": "Un résumé",
        "A resume": "Un CV",
        "Owing to": "À cause de",
        "Forecast": "Prédiction",
        "Mitigation": "Réduction",
        "Offset": "Compenser",
        "To brag": "Se vanter",
        "To downplay": "Minimiser",
        "To coin a word": "Inventer un mot",
        "A main culprit": "Un responsable principal",
        "To lobby": "Faire pression",
        "On behalf of": "De la part de",
        "Utter": "Complet",
        "Swift": "Rapide",
        "Advocate": "Prôner",
        "To stage": "Organiser",
        "Supply": "Approvisionnement",
        "Entangle": "Emmêler",
        "Purpose": "But",
        "Meddle": "Interférer",
        "To what extent": "Dans quelle mesure",
        "To impede": "Bloquer",
        "Tackles": "Aborder",
        "Offspring": "Descendance",
        "To pour": "Verser",
        "Aisles": "Allées",
        "Props": "Accessoires",
        "Stain": "Tacher",
        "Landscape": "Paysage",
        "Uprising": "Émeute",
        "Thus": "Ainsi",
        "Defiling": "Profanation/souillée",
        "The depletion": "L'épuisement",
        "Scarcity": "La rareté",
        "Raw materials": "Matière première",
        "Although": "Bien que",
        "Pristine": "Vierge",
        "Fourfold": "Quadruple",
        "A mammal": "Un mammifère",
        "Dwells at length": "S'étend sur une longue durée",
        "To funnel": "Diriger",
        "Readily": "Facilement",
        "Intermingled": "Entremêlées",
        "Such as": "Tel que",
        "Neglect": "Négligence",
        "Logging": "Exploitation du bois",
        "Pitches": "Emplacement",
        "To loosen": "Relâcher",
        "To halt": "Arrêter",
        "Overshoot": "Dépassement"}
const CH2 = {
        "endangered species":"espece en voie d extinction",
          "Supply": "Alimenter",
          "Plants": "Usines",
          "Meander": "Méandres",
          "To wean": "Sevrer",
          "Foreign / from abroad": "Étranger",
          "Straight": "Rectiligne",
          "Greenhouses": "Des serres",
          "Sustainable": "Durable",
          "To fear": "Craindre",
          "To provide somebody with": "Fournir quelque chose à quelqu'un",
          "Dependent": "Dépendre",
          "Cut down on": "Réduire",
          "To arouse": "Susciter",
          "To praise": "Faire l’éloge de",
          "Give birth to": "Donner naissance à",
          "Blueprint": "Projet / Schéma",
          "To postpone": "Remettre à plus tard",
          "The shape": "La forme",
          "Currently": "Actuellement",
          "Self-sufficient": "Auto-suffisant",
          "To encounter": "Rencontrer",
          "Draught": "Sécheresse",
          "Shortage": "Pénurie",
          "To address an issue": "S’attaquer à un problème",
          "To design": "Concevoir",
          "To wean somebody off": "Sevrer quelqu'un de quelque chose",
          "Activist": "Militants",
          "Linger": "Rester",
          "Sinking": "S'enfoncer",
          "Beneath": "Sous",
          "Collapsing": "S’effondrer",
          "Subsidence": "Affaissement",
          "Shift": "Changement",
          "Bearing": "Le support",
          "Low-lying": "Position basse",
          "Mitigation": "Atténuation",
          "Coastal": "Côtière",
          "Silt": "La vase",
          "Draining": "Évacuation",
            "The British economy": "L'économie britannique",
            "Economics": "L'économie (science)",
            "Liberalism, free enterprise": "Le libéralisme",
            "A free trade": "Le libre-échange",
            "A free-marketeer": "Un partisan du libéralisme",
            "A planned economy": "Une économie planifiée",
            "A state-run economy": "Une économie dirigée par l'État",
            "A state-owned company": "Une entreprise publique",
            "To intervene": "Intervenir",
            "State intervention(ism)": "Le dirigisme",
            "The law of supply and demand": "La loi de l'offre et la demande",
            "To nationalize": "Nationaliser",
            "To privatize": "Privatiser",
            "Capitalism": "Capitalisme",
            "Figure stuff out": "Comprendre les choses",
            "Rental": "Location",
            "Bevy": "Palette",
            "Feedback": "Retour",
            "Feedback loops": "Boucles de rétroaction",
            "Ownership": "Possession",
            "Agriculture / farming": "L'agriculture",
            "To produce": "Produire",
            "A producer": "Un producteur",
            "Agricultural produce": "Les produits agricoles",
            "A crop": "Une culture",
            "To grow corn": "Cultiver le blé/maïs",
            "The food processing industry": "L'agroalimentaire",
            "Organic farming": "L'agriculture biologique",
            "GMOs / genetically modified organisms": "Les OGM",
            "To breed cattle": "Élever du bétail",
            "Cattle breeding": "L'élevage du bétail",
            "A slaughterhouse": "Un abattoir",
            "Fishing": "La pêche",
            "A fish factory": "Une conserverie",
            "Recession / a slump": "Récession / dépression / régression économique",
            "Set off": "Déclencher",
            "Plummeted / to slump / to collapse / to plunge / to tumble": "S'effondrer",
            "Wages": "Salaires",
            "Pulled down": "Entraîné",
            "The manufacturing sector / the second sector": "Le secteur secondaire, l'industrie",
            "An industrialization": "Une industrialisation",
            "Deindustrialization": "La désindustrialisation",
            "A factory / plants": "Une usine",
            "A workshop": "Atelier",
            "Raw materials": "Les matières premières",
            "A foreman": "Un contremaître",
            "To manufacture": "Fabriquer",
            "To mass produce": "Fabriquer en série",
            "The output": "La production",
            "A machine tool": "Une machine-outil",
            "To operate a machine": "Faire fonctionner une machine",
            "To meet safety standards": "Respecter les normes de sécurité",
            "Heavy industry": "L'industrie lourde",
            "The textile industry": "L'industrie du textile",
            "The shipbuilding industry": "La construction navale",
            "Pharmaceuticals": "L'industrie pharmaceutique",
            "A car maker, a car manufacturer": "Un constructeur automobile",
            "Car making": "La construction automobile",
            "To automate": "Automatiser",
            "To dismantle": "Démanteler",
            "The service industries": "Les services, le tertiaire",
            "Physical goods": "Biens physiques",
            "A company / a firm": "Une entreprise",
            "A make, a brand": "Une marque",
            "To set up a company": "Fonder / Monter une entreprise",
            "To run a business": "Diriger une entreprise",
            "SMEs, small and medium-sized companies": "Les PME (Petites et Moyennes Entreprises)",
            "To compete with somebody": "Être en concurrence avec quelqu'un",
            "A competitor": "Un concurrent",
            "Competitiveness": "La compétitivité",
            "Unfair competition": "La concurrence déloyale",
            "To corner a market": "Accaparer un marché",
            "To break into a market / a market share": "Percer un marché / Une part de marché",
            "A merger": "Fusion d'entreprises",
            "To make profit": "Réaliser des bénéfices",
            "A loss": "Une perte",
            "To go bankrupt": "Faire faillite",
            "Debt": "Une dette",
            "Whose core": "Dont le noyau / l'essence",
            "Whether": "Si",
            "Left-wing policies": "Politiques de gauche",
            "Case in point": "Exemple",
            "A staunch": "Fervent",
            "A downturn, a downswing": "Une phase de baisse",
            "To fall / to slide / to decrease / to drop": "Baisser / Diminuer",
            "A slowdown": "Un ralentissement",
            "To go through a bad patch": "Connaître une période difficile",
            "The global economic meltdown": "L'effondrement de l'économie mondiale",
            "To streamline": "Rationaliser",
            "To downsize": "Dégraisser ses effectifs",
            "Restructuring": "Restructuration",
            "To make workers redundant, to lay off workers": "Licencier des salariés",
            "To cut jobs": "Supprimer des emplois",
            "Job losses": "Perte d'emplois",
            "A glimpse": "Un aperçu",
            "Resurgent": "Renaissant",
            "Pervasive": "Envahissant",
            "Seldom": "Rarement",
            "Faith": "Foi",
            "Maintains": "Soutient",
            "The economy is recovering": "L'économie se redresse",
            "Recovery": "La reprise",
            "Business is picking up": "Les affaires reprennent",
            "An upswing in economic growth": "Une remontée de la croissance",
            "To increase / to go up / to rise": "Augmenter / Élever",
            "To soar, to rocket": "Monter en flèche",
            "An exporter": "Un exportateur",
            "The balance of trade": "La balance commerciale",
            "Trade figures": "Les chiffres du commerce extérieur",
            "A deficit / a surplus": "Un déficit / Un excédent",
            "Tariffs": "Tarifs douaniers",
            "Trade barriers": "Les barrières douanières",
            "A trade war": "Une guerre commerciale",
            "As measured by weighting": "Tel que mesuré par pondération",
            "Dizzying": "Étourdissant",
            "Swept": "Balayé",
            "Swept back": "Est revenu",
            "Upbeat": "Optimiste",
            "To boost growth": "Stimuler la croissance",
            "Austerity measures": "Des mesures d'austérité",
            "A stimulus plan / package": "Un plan de relance",
            "A rescue package": "Un plan de sauvetage",
            "To deregulate": "Déréglementer",
            "Deregulation": "La déréglementation",
            "To bail out a company": "Renflouer une entreprise",
            "A subsidy": "Une subvention",
            "To subsidize": "Subventionner",
            "Growth": "La croissance",
            "Public spending": "Les dépenses publiques",
            "To balance a budget": "Équilibrer un budget",
            "Drastic budget cuts": "Réduction budgétaire",
            "A budget deficit": "Un déficit budgétaire",
            "A credit-rating agency": "Une agence de notation",
            "A tax rise": "Une augmentation des impôts",
            "Investment": "L'investissement",
            "Consumer spending / demand": "Les dépenses / la demande des consommateurs",
            "Janus-faced": "Ayant deux aspects",
            "The bounds": "Les limites",
            "Forestall": "Prévenir",
            "Harbingers": "Signes avant-coureurs",
            "To have your back to the wall": "Être dos au mur",
            "To close shop": "Fermer boutique",
            "A lame duck": "Un canard boiteux",
            "sidewalk/pavement": "trottoir",
    "to underrate / to underestimate": "sous-estimer",
    "clay": "argile",
    "silt": "limon",
    "awareness campaign": "campagne de sensibilisation",
    "be it": "que ce soit",
    "research": "les recherches",
    "asbestos": "amiante",
    "harmful effects/damaging effects": "méfait",
    "any": "n’importe quel",
    "city-dweller": "citadin",
    "to crave for / yearn for": "aspirer",
    "the countryside": "la campagne",
    "the hustle and bustle": "le tumulte",
    "a low traffic neighbourhood scheme": "un projet de quartier à faible trafic",
    "to throw sbdy out of work": "mettre qq’un au chômage",
    "shopkeeper/shop-owner": "commerçant",
    "dormitory town": "ville dortoir",
    "real estate": "l’immobilier",
    "let’s not become": "ne devenons pas",
    "motorist": "automobiliste",
    "biker": "motard",
    "congestion charge": "taxe d’embouteillage",
    "can’t afford": "ne pas pouvoir se permettre",
    "to afford": "avoir les moyens de",
    "to get sbdy into trouble": "attirer des ennuis à qq’un",
    "distrust/mistrust": "méfiance",
    "be locked up": "être enfermé",
    "broad": "large",
    "rely on": "dépendre de",
    "to meander / to wind": "ne pas aller droit",
    "wean": "sevrer",
    "crops": "des cultures",
    "water supply": "alimentation en eau",
    "feasible": "faisable",
    "be worried about / be concerned about": "être inquiet",
    "arouse": "susciter",
    "fear": "craindre",
    "to be drawn to": "être attiré par",
    "the engine-rooms of sthg": "le moteur de",
    "to keep up with": "rester à niveau de",
    "to refurbish / renovate": "rénover",
    "an estate agent": "agent immobilier",
    "vacant": "vide",
    "be prone to / be likely to": "être à même de",
    "to commute": "voyage régulier",
    "urban sprawl": "étalement urbain",
    "threshold": "seuil",
    "derelict": "tomber en lambeaux",
    "to sidestep / to bypass": "contourner",
    "brownfield site": "friche industrielle",
    "to unveil": "révéler",
    "their peers": "leur semblable",
    "unappealing / unattractive": "pas attirant",
    "to boast sthg": "être fier d’avoir",
    "weary": "lassé de",
    "storey": "étage",
    "a borough": "zone administrative",
    "to trade": "échanger",
    "to dent": "cabosser",
    "that barely dents": "cela n’entame guère",
    "to slam": "critiquer",
    "to challenge": "remettre en question",
    "footfall": "nombre de clients",
    "to halve": "diviser par deux",
    "a ticket can mean a fine": "une amende",
    "barely": "à peine",
    "to warp": "déformer",
    "throngs of tourists": "des hordes de touristes",
    "traffic jam/tailback": "les embouteillages",
    "to frown": "froncer les sourcils",
    "to frown upon sthg": "désapprouver",
    "bumper to bumper": "être cul à cul",
    "a fee": "une taxe",
    "one cannot but wonder": "on ne peut que se demander",
    "to wreak havoc with sthg": "causer des dommages",
    "to queue up": "faire la queue",
    "detrimental": "préjudiciable",
    "to distort": "modifier",
    "a hurdle": "obstacle",
    "a trend / tendency": "une tendance",
    "earnings / income": "les entrées d’argent",
    "at odds with": "être en contradiction",
    "a glimmer of hope": "une lueur d’espoir" 
      }
      
const CH3 = {
  "Standard of Living": "Le niveau de vie",
  "Living Standard": "Le niveau de vie",
  "GDP Per Head": "Le PIB par habitant",
  "GDP Per Inhabitant": "Le PIB par habitant",
  "Lifestyle": "Mode de vie",
  "Way of Life": "Mode de vie",
  "Buying Power": "Le pouvoir d'achat",
  "Spending Power": "Le pouvoir d'achat",
  "Purchasing Power": "Le pouvoir d'achat",
  "Rich": "Riche",
  "Wealthy": "Riche",
  "Wealth": "La richesse",
  "Affluent": "La richesse",
  "Well Off": "Aisé",
  "Well To Do": "Nanti",
  "Well Heeled": "Fortuné",
  "Affluent Society": "La société d'abondance",
  "To Be Affluent": "Vivre dans l'aisance",
  "Influenza": "Grippe",
  "Portmanteau Word": "Mot composé de deux autres",
  "Unfulfilled": "Frustré",
  "Spite": "Dépit",
  "Well Being": "Le bien-être",
  "Rich People": "Les riches",
  "The Rich": "Les riches",
  "Riches": "Des richesses",
  "Super Rich": "Les grandes fortunes",
  "Mega Rich": "Les grandes fortunes",
  "Stinking Rich": "Plein aux as",
  "In Moneyed Circles": "Parmi les riches",
  "Amass": "Amasser",
  "A Millionaire": "Un millionnaire",
  "Dollar Millionaire": "Un millionnaire en dollars",
  "A Billionaire": "Un milliardaire",
  "Zillionaire": "Un multimilliardaire",
  "Multi Millionaire": "Un multimilliardaire",
  "Oil Magnate": "Un magnat du pétrole",
  "Press Baron": "Un baron de la presse",
  "Media Mogul": "Un magnat des médias",
  "Software Tycoon": "Un roi des logiciels",
  "Income": "Le revenu",
  "Income Tax": "L'impôt sur le revenu",
  "Tax Haven": "Un paradis fiscal",
  "Tax Evasion": "La fraude fiscale",
  "Stash Money Away": "Planquer de l'argent",
  "Money Laundering": "Le blanchiment d'argent",
  "High Income Families": "Familles à hauts revenus",
  "Low Income Families": "Familles à bas revenus",
  "Taxpayer": "Un contribuable",
  "Earnings": "Les gains",
  "Shell Companies": "Sociétés écrans",
  "The Laundromat": "Laundromat",
  "Poverty": "La pauvreté",
  "Poor People": "Les pauvres",
  "Working Poor": "Les travailleurs pauvres",
  "Poor": "Pauvre",
  "Impoverished": "Pauvre",
  "The Needy": "Les nécessiteux",
  "Dire Poverty": "La misère",
  "Destitution": "La misère noire",
  "Most Destitute": "Les plus démunis",
  "To Fall On Hard Times": "Tomber dans la misère",
  "To Sink Into Poverty": "Sombrer dans la pauvreté",
  "Below The Poverty Line": "En dessous du seuil de pauvreté",
  "Above The Poverty Line": "Au-dessus du seuil de pauvreté",
  "Low Income Household": "Un ménage à revenu modeste",
  "Deprived": "Défavorisé",
  "Disadvantaged": "Défavorisé",
  "Underprivileged": "Défavorisé",
  "To Live On 2 A Day": "Vivre avec 2 $ par jour",
  "To Live On Benefit": "Vivre d'allocations",
  "On Welfare": "Vivre d'allocations",
  "Pauperism": "Le paupérisme",
  "Pauperization": "La paupérisation",
  "Mind Bending": "Hallucinant",
  "Everyone But": "Sauf",
  "In The Span": "L'espace",
  "Inequality": "L'inégalité",
  "Unequal": "Inégal",
  "To Share": "Partager",
  "To Share Out": "Répartir",
  "Distribution Of Wealth": "La répartition des richesses",
  "Two Tier Society": "Une société à deux vitesses",
  "Social Fabric": "Le tissu social",
  "Gap Between Rich And Poor": "Le fossé entre les riches et les pauvres",
  "Gap Between Haves And Have Nots": "La fracture sociale",
  "To Bridge The Gap": "Combler le fossé",
  "Gap Closing": "Le fossé se comble",
  "Gap Widening": "Le fossé se creuse",
  "Discrepancy": "Un écart",
  "Chasm": "Un gouffre",
  "Balance": "L'équilibre",
  "Imbalance": "Le déséquilibre",
  "Balanced": "Équilibré",
  "Unbalanced": "Déséquilibré",
  "Redress Balance": "Rétablir l'équilibre",
  "Torn": "Déchiré",
  "Strife": "Rivalités",
  "Social Advancement": "La promotion sociale",
  "Career Advancement": "L'ascension professionnelle",
  "Professional Advancement": "L'ascension professionnelle",
  "Social Ladder": "L'ascenseur social",
  "To Move Up Social Ladder": "Monter dans l'échelle sociale",
  "Upward Social Mobility": "L'ascension sociale",
  "Self Made Man": "Une personne qui s'est faite elle-même",
  "Rags To Riches Story": "L'histoire d'un pauvre devenu riche",
  "To Start From Scratch": "Partir de rien",
  "To Strike Gold": "Faire fortune",
  "To Strike It Rich": "Faire fortune",
  "Equality Of Opportunity": "L'égalité des chances",
  "Egalitarian": "Égalitaire",
  "Egalitarianism": "L'égalitarisme",
  "Social Standing": "Le niveau social",
  "Social Status": "Le statut social",
  "Fall In Status": "Le déclassement",
  "Social Descent": "Le déclassement",
  "Scrambled": "Bouleversée",
  "Decline In Living Standards": "Une baisse du niveau de vie",
  "To Struggle To Get By": "Peiner à s'en sortir",
  "Difficulty Paying Bills": "Avoir du mal à payer les factures",
  "To Make Ends Meet": "Joindre les deux bouts",
  "To Live Hand To Mouth": "Vivre le jour le jour",
  "To Scrape By": "Vivoter",
  "To Survive": "Survivre",
  "Homeless": "Sans abris",
  "Homelessness Is On The Rise": "Il y a de plus en plus de sans abris",
  "Tramp": "Un clodo",
  "Bum": "Un clodo",
  "Bag Lady": "Une clocharde",
  "Soup Kitchen": "Une soupe populaire",
  "Bread Line": "Une soupe populaire",
  "Underclass": "Le quart-monde",
  "Slum": "Un taudis",
  "To Tighten Your Belt": "Se serrer la ceinture",
  "To Be On Shoestring": "Vivre avec peu d'argent",
  "From Rags To Riches": "Passer de la misère à la richesse",
  "Fat Cat": "Un gros richard",
      "asset": "actif",
      "stockbroker": "coursier",
      "relieving": "soulager",
      "a cure": "un remède",
      "rather": "un peu/plutôt",
      "pun/wordplay": "un jeu de mots",
      "scales": "balance",
      "change": "monnaie",
      "to tip": "faire pencher la balance",
      "embodying": "incarner",
      "therefore": "par conséquent",
      "the haves and the have-nots": "les riches et les pauvres",
      "expect": "attendre quelque chose de quelqu’un",
      "scorn": "le mépris",
      "unfair": "injuste",
      "hierarchy": "hiérarchie",
      "educated": "éduqués",
      "overall": "générale",
      "abortion": "avortement",
      "dismal": "mauvais",
      "their peers": "leurs semblables",
      "tremendously": "énormément",
      "medicaid": "aide médicale",
      "condition": "maladie",
      "trickle": "le ruissèlement",
      "triggered": "causé",
      "hand in hand": "de main en main",
      "surge": "augmente",
      "involvement in/commitment to": "s’engager dans",
      "a beggar": "un mendiant",
      "to deride": "se moquer de",
      "a scathing criticism": "une critique acerbe",
      "one cannot but notice": "on ne peut que remarquer",
      "to fulfil": "réaliser",
      "to strive": "s’efforcer de"
  
}

const CH4 =
{
  
  "The press/ the print media": "la presse écrite",
        "A newspaper/a paper": "un journal",
        "A gloosy magazine": "un magazine de luxe",
        "A journal": "un magazine (sérieux)",
        "A journalist/a newsman/a commentator": "un journaliste",
        "A columnist": "un chroniqueur",
        "A correspondent": "un correspondant",
        "A reporter": "un reporter",
        "A report": "un reportage",
        "To report on sth": "faire un reportage sur quelque chose",
        "To inform": "informer",
        "To investigate": "mener une enquête",
        "To cover an event": "couvrir un événement",
        "Media coverage": "la couverture médiatique",
        "The gutter press": "presse à sensation",
        "A news agency, a press agency": "une agence de presse",
        "A news-stand": "un kiosque à journaux",
        "A newsagent": "un marchand de journaux",
        "A newspaper proprietor": "un propriétaire de journal",
        "Latter": "dernier",
        "A press baron/a press tycoon/a press magnate/A media mogul": "un magnat des médias",
        "To publish": "publier",
        "To print": "imprimer",
        "Hype": "le battage médiatique",
        "Journalese": "le jargon des journalistes",
        "An evening/a morning paper": "un journal du matin/soir",
        "A Sunday paper": "un journal du dimanche",
        "Daily/weekly/monthly": "quotidien/hebdomadaire/mensuel",
        "The headlines": "les gros titres",
        "To hit the headlines": "faire les gros titres",
        "The front-page": "la première page",
        "An editorial/a leading article/a leader": "un éditorial",
        "An editor, a chief editorial": "rédacteur en chef",
        "The business section": "les pages affaires",
        "A book/film review/A literary": "une critique de livre/film",
        "Small ads, personal ads": "les petites annonces",
        "Agony column": "le courrier du cœur",
        "A graph, a chart": "un graphique/un diagramme",
        "A pie chart": "un diagramme camembert",
        "A cartoon": "un dessin humoristique",
        "A caption": "une légende (petit texte)",
        "The comics": "BD",
        "Bribery": "corruption",
        "Outcry": "tollé",
        "To subscribe to a magazine/to take out": "s’abonner",
        "A subscriber": "un abonné",
        "Readership": "le lectorat/nombre de lecteurs",
        "Circulation": "tirage",
        "A copy": "un exemplaire",
        "An issue": "un numéro",
        "A newspaper cutting": "une coupure de journal",
        "Commoners": "roturiers",
        "Current events/current affairs": "l’actualité",
        "A news item": "une information",
        "A topical issue": "un sujet d’actualité",
        "A scoop": "un scoop",
        "To reveal": "dénoncer",
        "A leak": "une fuite",
        "Check/disclose one’s sources": "vérifier/révéler ses sources",
        "A disclosure": "la révélation/divulgation",
        "Reliable": "fiable",
        "Biased/prejudiced/partial": "partial",
        "Draft": "version",
        "Steeply": "fortement",
        "Broadcast media": "radio et télé",
        "Satellite/cable television": "la télé",
        "A programme/a program": "une émission",
        "Prime time": "les heures d’écoute",
        "A TV show": "une émission télé",
        "A talk show/a chat show": "un débat",
        "A host/an anchorman": "présentateur",
        "A soap/a serial": "un feuilleton",
        "A phone-in": "fait participer les téléspectateurs",
        "Reality TV": "télé réalité",
        "Live": "direct",
        "A news bulletin": "un bulletin d’information",
        "A news flash": "un flash d'information",
        "A newsreader/a newscaster": "un présentateur du journal",
        "To watch the news": "regarder les infos",
        "A current affairs programme": "une émission d’actualités",
        "A documentary": "un documentaire",
        "A TV viewer": "un téléspectateur",
        "A couch potato": "quelqu’un qui reste dans son canapé",
        "A listener": "un auditeur",
        "Audience ratings/figures": "l’audimat",
        "A commercial": "un spot publicitaire",
        "A commercial break": "une page de pub",
        "To broadcast": "diffuser",
        "Privacy": "la vie privée",
        "Breach of privacy": "atteinte à la vie privée",
        "Libel": "la diffamation",
        "Slander": "la calomnie",
        "To censor": "censurer",
        "Censorship": "la censure",
        "To circumvent/bypass censorship": "contourner la censure",
        "To sound/to ring the alarm bell": "tirer la sonnette d’alarme",
        "To blow the whistle on sb": "dénoncer quelqu’un",
        "A whistleblower": "un lanceur d’alerte",
        "To censor": "censurer",
  "Censorship": "la censure",
  "To circumvent/bypass censorship": "contourner la censure",
  "To sound/to ring the alarm bell": "tirer la sonnette d’alarme",
  "To blow the whistle on sb": "dénoncer quelqu’un",
  "A whistleblower": "un lanceur d’alerte",
  "to gag": "bâillonner",
  "a gag": "un bâillon",
  "Foul": "répugnant",
  "Conveyor belt": "tapis roulant",
  "Mass-produced cartoons": "dessins animés produits en masse",
  "electric-powered machines": "machines alimentées par électricité",
  "hand-made cartoons": "dessins animés faits à la main",
  "hand-crafted art": "art fait à la main",
  "profit-making business": "entreprise à but lucratif",
  "an awareness-raising cartoon": "un dessin animé de sensibilisation",
  "Objectionable": "répréhensible",
  "To censor (vb)": "censurer",
  "Censorship (nom)": "censure",
  "Dystopian": "dystopique",
  "To be PC": "être politiquement correct",
  "Political correctness": "le politiquement correct",
  "To serve as an eye-opener on sthg": "provoquer une prise de conscience à propos de / ouvrir les yeux sur",
  "The scope of": "la portée de",
  "A bogeyman": "quelqu'un ou quelque chose qui est considéré comme effrayant ou menaçant (le croque-mitaine est un personnage imaginaire utilisé pour effrayer les enfants)",
  "From all walks of life": "cette expression fait référence à des personnes de différents horizons et milieux, avec des emplois variés et de différents niveaux sociaux",
  "To track": "suivre",
  "Aban": "abandonné",
  "Aveil": "évêque (il semble qu'il y ait une faute de frappe ici, peut-être voulais-tu dire 'avail' ou un autre mot ?)",
  "Librarian / Library": "bibliothécaire / bibliothèque",
  "Bookseller / Bookshop": "libraire / librairie",
  "To jeer at": "se moquer de, rire de, railler (jeer at est moins poli que laugh at ou make fun of)",
  "To exert": "exercer (une censure, une influence, une autorité …)",
  "To target": "cibler",
  "Gender-affirming (literature …)": "affirmant le genre (littérature …)",
  "To do sthg under false pretences / pretenses": "faire quelque chose sous de fausses apparences / prétextes : mentir sur qui vous êtes, ce que vous faites ou vos intentions réelles",
  "To be non-committal": "ne pas prendre position, être indécis",
  "To be biased about sthg": "être partial à propos de quelque chose",
  "The Proud Boys": "un groupe d'extrême droite",
  "a far-right group": "un groupe d'extrême droite",
  "the threats looming over them": "les menaces qui pèsent sur eux",
  "a journey": "un voyage",
  "on a quest for": "en quête de",
  "to uphold": "soutenir, défendre (une idée, une théorie, mais pas quelqu'un : défendre quelqu'un)",
  "Silliness": "imbécillité",
  "Disturbing": "dérangeant",
  "Trend": "tendance",
  "Palatable": "acceptable, agréable au goût",
  "wise": "sage / judicieux",
  "wisdom": "sagesse",
  "wig": "perruque",
  "to meddle (in / with sthg)": "mêler, se mêler de quelque chose",
  "blowback effect / backlash": "réaction en retour / répercussion",
  "the range of / the scope of": "la portée de",
  "to undermine / to erode / to destroy sthg slowly": "saper / éroder / détruire quelque chose lentement",
  "to deter sbdy FROM Ving": "dissuader quelqu'un de faire quelque chose",
  "an impediment to progress": "un obstacle au progrès",
  "to sanitize": "assainir, purifier",
  "to run counter to sthg": "aller à l'encontre de quelque chose",
  "to foster sthg": "encourager quelque chose",
  "staunch": "ferme, inébranlable",
  "to discredit": "discréditer",
  "to disparage": "dénigrer",
  "a stance (on sthg)": "une position (sur quelque chose)",
  "To stifle": "étouffer",
  "to distort": "déformer",
  "hold up a mirror to sthg": "être le miroir de quelque chose",
  "to be reminiscent of sthg": "rappeler quelque chose",
  "to resort to": "recourir à",
  "to offend": "vexer",
  "to fetter / to shackle": "être un obstacle à quelque chose, restreindre quelque chose (comme un prisonnier portant des chaînes)",
  "ludicrous": "absurde",
  "pointless": "inutile",
  "the emergence of": "l'apparition de",
  "to circumvent": "contourner",
  "to comply with": "se conformer à",
  "uselessness": "inutilité",
  "it is detrimental to sth": "c'est nuisible à quelque chose",
  "prominent": "prominent, important",
  "the line is blurred": "la frontière est floue",
  "to puzzle sb": "perplexer quelqu'un",
  "to curb": "freiner",
  "parent company": "maison mère",
  "half as many + pluriel": "deux fois moins de (pluriel)",
  "half as much + singulier": "deux fois moins de (singulier)",
  "the share of": "la part de",
  "hateful content": "contenu haineux",
  "hate speech": "propos haineux",
    "censurer": "To censor",
    "Censorship":"la censure",
      "Swear words": "",
      "Cliff": "falaise",
      "Devices": "appareils",
      "Non-committal": "neutre",
      "Dictatorship": "dictature",
      "Stance position": "position tranchée",
      "It’s more of a": "c’est plus",
      "All the more": "d’autant",
      "Hence": "d’où",
      "Foul": "idiot",
      "Seldom": "rarement",
      "Patchy": "incomplet",
      "Applied for": "postuler",
      "Meager": "simple",
      "To puzzle sb": "rendre confus",
      "To curb": "réduire",
      "The share of": "proportion",
      "Ludicrous": "ridicule",
      "To stifle": "limiter",
      "To resort to": "utiliser",
      "To fetter/to shackle": "enchaîner",
      "The line is blurred": "la ligne est floue",
      "To comply with": "être conforme à",
      "Self defeating/counter productif": "contre-productif",
      "To distinguish": "distinguer",
        "to abide by sthg": "se conformer à, obéir à, se plier à",
        "to flag": "signaler",
        "a slur": "une insulte, une remarque désobligeante",
        "'cracker' is a slur in some southern US states where it refers to poor white people.": "'cracker' est une insulte dans certains États du sud des États-Unis où il désigne les blancs pauvres.",
        "advocacy group": "groupe de défense",
        "a fool's errand": "une tâche vouée à l'échec",
        "to blast sbdy": "critiquer",
        "a manifesto": "un manifeste",
        "to spot": "repérer",
        "unprecedented": "sans précédent",
        "to have one's account deleted": "se faire effacer son compte",
        "a critical avenue": "un lieu majeur, un espace important, un moyen essentiel",
        "ongoing efforts": "efforts soutenus, continus, en cours",
        "gatekeeper": "gardien, contrôleur d’accès",
        "a quarter": "un trimestre"
       
      
    }
let ch5 = {
  "Food": "la nourriture",
  "Foodstuffs": "les denrées alimentaires/les aliments",
  "To feed oneself on sth": "se nourrir de qch",
  "To cook": "cuisiner",
  "To do the cooking": "faire la cuisine",
  "Eating habits": "les habitudes alimentaires",
  "Eating patterns": "les habitudes alimentaires",
  "Fruit and vegetable intake": "la consommation de fruits et de légumes",
  "Daily salt intake": "la consommation quotidienne de sel",
  "Diagnose": "diagnostiquer",
  "Obtained": "obtenu",
  "Weight": "le poids",
  "To weigh oneself": "se peser",
  "To weigh": "peser",
  "To put on weight": "prendre du poids",
  "To gain weight": "prendre du poids",
  "To lose weight": "perdre du poids",
  "Outbreak": "épidémie",
  "Disorder": "trouble",
  "Stomach": "l’estomac",
  "Gut": "l’intestin",
  "Liver": "le foie",
  "To be overweight": "être en surpoids",
  "To be ten kilos overweight": "avoir dix kilos de trop",
  "Fat": "gros/gras",
  "Obese": "obèse",
  "Obesity": "l’obésité",
  "Childhood obesity": "l’obésité des enfants",
  "Plump": "dodu",
  "Stout": "corpulent",
  "Corpulent": "corpulent",
  "The waistline": "le tour de taille",
  "Flab": "la graisse superflue",
  "A paunch": "une bedaine",
  "Bulimia": "la boulimie",
  "Bulimic": "boulimique",
  "To be a compulsive eater": "ne pas pouvoir s’empêcher de manger",
  "To binge on chocolate": "s’empiffrer de chocolat",
  "Binge eating": "l’excès de nourriture",
  "Binge drinking": "les excès de boisson",
  "To go on a binge": "faire des excès",
  "To resist temptation": "résister à la tentation",
  "To give in to temptation": "céder à la tentation",
  "Dined": "dîné",
  "Sampling": "goûtant",
  "Well-being": "bien-être",
  "Mood swings": "sautes d’humeur",
  "Liver damage": "problème de foie",
  "A chocolate bar": "une barre chocolatée",
  "A chocaholic": "un accro au chocolat",
  "To be addicted to sth": "être accro à qch",
  "Addiction": "l’accoutumance, la dépendance",
  "Addictive": "qui crée une accoutumance, addictogène",
  "Triggers": "déclenche",
  "Decipher": "déchiffrer",
  "Whether": "si",
  "Reigning": "régnante",
  "Thin": "maigre",
  "Skinny": "magrichon",
  "Scrawny": "magrichon",
  "To be lean and muscular": "être mince et musclé",
  "Bony": "décharné",
  "Slim": "mince",
  "Slender": "svelte",
  "Svelte": "svelte",
  "To be underweight": "être trop maigre",
  "How to stick to": "s’en tenir à",
  "Anorexia": "l’anorexie",
  "Anorexic": "anorexique",
  "To develop anorexia": "devenir anorexique",
  "To starve oneself to death": "se laisser mourir de faim",
  "Meat": "la viande",
  "Veggies": "les légumes",
  "Greens": "les légumes",
  "Carbohydrates": "glucides",
  "Carbs": "glucides",
  "Starch": "l’amidon",
  "Fiber": "fibre",
  "To go on a diet": "commencer un régime",
  "To be on a diet": "faire un régime",
  "A slimming diet": "régime amaigrissant",
  "A healthy diet": "une alimentation saine",
  "Balanced diet": "une alimentation bien équilibrée",
  "Unbalanced diet": "une alimentation mal équilibrée",
  "Diet foods": "aliments faibles en calories",
  "Health foods": "les aliments diététiques",
  "A health food shop": "un magasin de produits diététiques",
  "Organic food": "la nourriture biologique, les aliments bio",
  "An organic restaurant": "un restaurant diététique",
  "Vegetarian": "végétarien",
  "A nutritionist": "un nutritionniste",
  "A dietician": "un diététicien",
  "A dietitian": "un diététicien",
  "Sedentary": "sédentaire",
  "A sedentary lifestyle": "la sédentarité",
  "To be fit": "être en forme",
  "To watch one’s figure": "surveiller sa ligne",
  "To keep one’s figure": "surveiller sa ligne",
  "A fitness": "la santé",
  "A fitness freak": "un mordu de culture physique",
  "To go to the gym": "aller à la muscu",
  "To be all skin and bones": "avoir la peau sur les os",
  "To fight the flab": "lutter contre les bourrelets",
  "To hit the bottle": "picoler",
  "The morning after the night before": "le lendemain d’une beuverie"
}
    




let list1 = document.getElementById('list1')
for (let clé in CH1) {
    console.log(1)
    list1.innerHTML += "<li class='mot_l'>"+clé+" : "+CH1[clé],"</li>"
}

let list2 = document.getElementById('list2')
for (let clé in CH2) {
    list2.innerHTML += "<li class='mot_l'>"+clé+" : "+CH2[clé],"</li>"
}

let list3 = document.getElementById('list3')
for (let clé in CH3) {
    list3.innerHTML += "<li class='mot_l'>"+clé+" : "+CH3[clé],"</li>"
}

let list4 = document.getElementById('list4')
for (let clé in CH4) {
    list4.innerHTML += "<li class='mot_l'>"+clé+" : "+CH4[clé],"</li>"
}

let list5 = document.getElementById('list5')
for (let clé in ch5) {
    list5.innerHTML += "<li class='mot_l'>"+clé+" : "+ch5[clé],"</li>"
}
