const mot = {
        "To smear something with": "Enduire",
        "To throw something at / to hurl something at": "Lancer quelque chose",
        "A painting": "Une peinture",
        "Paint": "De la peinture",
        "To make themselves heard": "Pour se faire entendre",
        "To make somebody aware of / to raise awareness": "Faire prendre conscience de",
        "To draw attention": "Attirer l'attention",
        "Demonstrators": "Manifestants",
        "To splash, to splatter something across": "Balancer",
        "Coffin": "Cercueil",
        "To cross": "Traverser",
        "Neither, nor": "Ni, ni",
        "To snore": "Ronfler",
        "Snoring": "Ronflement",
        "Puffy/swollen": "Bouffi",
        "Grown-up": "Grande personne",
        "To claim": "Réclamer",
        "Distraught": "Désespéré",
        "Game (hunting)": "Gibier",
        "Game-bag": "Carnier",
        "Cartridge": "Cartouche",
        "So as not to / in order not to": "Pour ne pas",
        "To refill/fill in": "Remplir",
        "Pale/dim": "Pâle",
        "Dawn": "Aube",
        "Blink/flicker": "Clignoter",
        "Shutter": "Volet",
        "To nail": "Clouer",
        "Bottle": "Biberon",
        "To outweigh / to be heavier": "Peser plus lourd",
        "Lack of": "Manquer de",
        "Further / to promote": "Promouvoir",
        "Sparked": "Déclenché",
        "Unless": "À moins que",
        "Timeless": "Intemporel",
        "Demonstration": "Manifestation",
        "Hold somebody accountable": "Tenir quelqu’un responsable",
        "Live on handouts": "Vivre des aides",
        "Western": "Occidental",
        "Wipe off": "Enlever",
        "To be unemployed": "Être au chômage",
        "Widespread": "Généralisé",
        "Harm somebody": "Nuire à quelqu’un",
        "Stunt": "Un coup de pub",
        "Slack": "Fainéant",
        "Sew": "Coudre",
        "To delay": "Reporter",
        "To summarize": "Résumer",
        "To resume": "Reprendre",
        "A summary": "Un résumé",
        "A resume": "Un CV",
        "Owing to": "À cause de",
        "Forecast": "Prédiction",
        "Mitigation": "Réduction",
        "Offset": "Compenser",
        "To brag": "Se vanter",
        "To downplay": "Minimiser",
        "To coin a word": "Inventer un mot",
        "A main culprit": "Un responsable principal",
        "To lobby": "Faire pression",
        "On behalf of": "De la part de",
        "Utter": "Complet",
        "Swift": "Rapide",
        "Advocate": "Prôner",
        "To stage": "Organiser",
        "Supply": "Approvisionnement",
        "Entangle": "Emmêler",
        "Purpose": "But",
        "Meddle": "Interférer",
        "To what extent": "Dans quelle mesure",
        "To impede": "Bloquer",
        "Tackles": "Aborder",
        "Offspring": "Descendance",
        "To pour": "Verser",
        "Aisles": "Allées",
        "Props": "Accessoires",
        "Stain": "Tacher",
        "Landscape": "Paysage",
        "Uprising": "Émeute",
        "Thus": "Ainsi",
        "Defiling": "Profanation/souillée",
        "The depletion": "L'épuisement",
        "Scarcity": "La rareté",
        "Raw materials": "Matière première",
        "Although": "Bien que",
        "Pristine": "Vierge",
        "Fourfold": "Quadruple",
        "A mammal": "Un mammifère",
        "Dwells at length": "S'étend sur une longue durée",
        "To funnel": "Diriger",
        "Readily": "Facilement",
        "Intermingled": "Entremêlées",
        "Such as": "Tel que",
        "Neglect": "Négligence",
        "Logging": "Exploitation du bois",
        "Pitches": "Emplacement",
        "To loosen": "Relâcher",
        "To halt": "Arrêter",
        "Overshoot": "Dépassement",
          "Supply": "Alimenter",
          "Plants": "Usines",
          "Meander": "Méandres",
          "To wean": "Sevrer",
          "Foreign / from abroad": "Étranger",
          "Straight": "Rectiligne",
          "Greenhouses": "Des serres",
          "Sustainable": "Durable",
          "To fear": "Craindre",
          "To provide somebody with": "Fournir quelque chose à quelqu'un",
          "Dependent": "Dépendre",
          "Cut down on": "Réduire",
          "To arouse": "Susciter",
          "To praise": "Faire l’éloge de",
          "Give birth to": "Donner naissance à",
          "Blueprint": "Projet / Schéma",
          "To postpone": "Remettre à plus tard",
          "The shape": "La forme",
          "Currently": "Actuellement",
          "Self-sufficient": "Auto-suffisant",
          "To encounter": "Rencontrer",
          "Draught": "Sécheresse",
          "Shortage": "Pénurie",
          "To address an issue": "S’attaquer à un problème",
          "To design": "Concevoir",
          "To wean somebody off": "Sevrer quelqu'un de quelque chose",
          "Activist": "Militants",
          "Linger": "Rester",
          "Sinking": "S'enfoncer",
          "Beneath": "Sous",
          "Collapsing": "S’effondrer",
          "Subsidence": "Affaissement",
          "Shift": "Changement",
          "Bearing": "Le support",
          "Low-lying": "Position basse",
          "Mitigation": "Atténuation",
          "Coastal": "Côtière",
          "Silt": "La vase",
          "Draining": "Évacuation"
        
        
      }
      
  


let list = document.getElementById('list')
for (let clé in mot) {
    list.innerHTML += "<p class='mot_l'>"+clé+" : "+mot[clé],"</p>"
}
