const mot = {
    "a file":"un dossiers",
    "at random":"au hazard",
    "on purpose":"de façon refléchit",
    "achivements":"réussite",
    "portrayal":"portrait",
    "incentive":"motivation",
    "for sure":"t'es sur",
    "hello": "bonjour",
  "world": "monde",
  "computer": "ordinateur",
  "cat": "chat",
  "dog": "chien",
  "house": "maison",
  "car": "voiture",
  "book": "livre",
  "flower": "fleur",
  "tree": "arbre",
  "friend": "ami",
  "family": "famille",
  "food": "nourriture",
  "water": "eau",
  "sun": "soleil",
  "moon": "lune",
  "stars": "étoiles",
  "music": "musique",
  "love": "amour",
  "happy": "heureux",
  "sad": "triste",
  "good": "bon",
  "bad": "mauvais",
  "help": "aider",
  "thank you": "merci",
  "please": "s'il vous plaît",
  "yes": "oui",
  "no": "non",
  "time": "temps",
  "day": "jour",
  "night": "nuit",
  "week": "semaine",
  "month": "mois",
  "year": "an",
  "money": "argent",
  "job": "travail",
  "school": "école",
  "teacher": "professeur",
  "student": "étudiant",
  "city": "ville",
  "country": "pays",
  "beach": "plage",
  "mountain": "montagne",
  "apple": "pomme",
  "banana": "banane",
  "orange": "orange",
  "grape": "raisin",
  "strawberry": "fraise",
  "vegetable": "légume",
  "computer": "ordinateur",
  "phone": "téléphone",
  "table": "table",
  "chair": "chaise",
  "pen": "stylo",
  "paper": "papier",
  "clock": "horloge",
  "watch": "montre",
  "shoes": "chaussures",
  "shirt": "chemise",
  "pants": "pantalon",
  "dress": "robe",
  "hat": "chapeau",
  "umbrella": "parapluie",
  "bicycle": "vélo",
  "car": "voiture",
  "bus": "autobus",
  "train": "train",
  "plane": "avion",
  "boat": "bateau",
  "book": "livre",
  "magazine": "magazine",
  "newspaper": "journal",
  "computer": "ordinateur",
  "internet": "Internet",
  "music": "musique",
  "movie": "film",
  "television": "télévision",
  "family": "famille",
  "brother": "frère",
  "sister": "sœur",
  "mother": "mère",
  "father": "père",
  "friend": "ami",
  "neighbor": "voisin",
  "doctor": "médecin",
  "hospital": "hôpital",
  "police": "police",
  "firefighter": "pompier",
  "bank": "banque",
  "post office": "poste",
  "restaurant": "restaurant",
  "hotel": "hôtel",
  "park": "parc",
  "beach": "plage",
  "mountain": "montagne",
  "river": "rivière",
  "computer": "ordinateur",
  "keyboard": "clavier",
  "mouse": "souris",
  "screen": "écran",
  "printer": "imprimante",
  "email": "courriel",
  "internet": "internet",
  "website": "site web",
  "password": "mot de passe",
  "camera": "appareil photo",
  "telephone": "téléphone",
  "headphones": "écouteurs",
  "music": "musique",
  "video": "vidéo",
  "friendship": "amitié",
  "happiness": "bonheur",
  "sadness": "tristesse",
  "success": "réussite",
  "failure": "échec",
  "hobby": "passe-temps",
  "travel": "voyage",
  "adventure": "aventure",
  "nature": "nature",
  "environment": "environnement",
  "science": "science",
  "history": "histoire",
  "art": "art",
  "culture": "culture",
  "language": "langue",
  "education": "éducation",
  "knowledge": "connaissance",
  "health": "santé",
  "medicine": "médecine",
  "exercise": "exercice",
  "food": "nourriture",
  "drink": "boisson",
  "coffee": "café",
  "tea": "thé",
  "breakfast": "petit déjeuner",
  "lunch": "déjeuner",
  "dinner": "dîner",
  "dessert": "dessert",
  "fruit": "fruit",
  "vegetable": "légume",
  "shopping": "shopping",
  "money": "argent",
  "wallet": "portefeuille",
  "bank": "banque",
  "business": "affaires",
  "job": "travail",
  "office": "bureau",
  "meeting": "réunion",
  "project": "projet",
  "team": "équipe",
  "leader": "leader",
  "customer": "client",
  "product": "produit",
  "service": "service",
  "house": "maison",
  "apartment": "appartement",
  "room": "chambre",
  "bathroom": "salle de bains",
  "kitchen": "cuisine",
  "living room": "salle de séjour",
  "bedroom": "chambre à coucher",
  "garden": "jardin",
  "street": "rue",
  "city": "ville",
  "country": "pays",
  "mountain": "montagne",
  "beach": "plage",
  "lake": "lac",
  "river": "rivière",
  "forest": "forêt",
  "park": "parc",
  "school": "école",
  "university": "université",
  "library": "bibliothèque",
  "hospital": "hôpital",
  "pharmacy": "pharmacie",
  "airport": "aéroport",
  "bus stop": "arrêt de bus",
  "train station": "gare de train",
  "restaurant": "restaurant",
  "cafe": "café",
  "bar": "bar",
  "store": "magasin",
  "market": "marché",
  "bank": "banque",
  "post office": "bureau de poste",
  "museum": "musée",
  "theater": "théâtre",
  "cinema": "cinéma",
  "concert": "concert",
  "sport": "sport",
  "football": "football",
  "basketball": "basket-ball",
  "tennis": "tennis",
  "swimming": "natation",
  "biking": "vélo",
  "hiking": "randonnée",
  "reading": "lecture",
  "writing": "écriture",
  "painting": "peinture",
  "music": "musique",
  "dance": "danse",
  "singing": "chant",
  "shopping": "shopping",
  "travel": "voyage",
  "holiday": "vacances",
  "passport": "passeport",
  "ticket": "billet",
  "map": "carte",
  "guidebook": "guide de voyage",
  "tourist": "touriste",
  "camera": "appareil photo",
  "photograph": "photographe",
  "video": "vidéo",
  "sunrise": "lever du soleil",
  "sunset": "coucher du soleil",
  "moonlight": "clair de lune",
  "stars": "étoiles",
  "clouds": "nuages",
  "rain": "pluie",
  "snow": "neige",
  "wind": "vent",
  "weather": "temps",
  "temperature": "température",
  "climate": "climat",
  "season": "saison",
  "spring": "printemps",
  "summer": "été",
  "autumn": "automne",
  "winter": "hiver",
  "day": "jour",
  "night": "nuit",
  "morning": "matin",
  "afternoon": "après-midi",
  "evening": "soirée",
  "week": "semaine",
  "month": "mois",
  "year": "année",
  "century": "siècle",
  "history": "histoire",
  "future": "avenir",
  "past": "passé",
  "present": "présent",
  "space": "espace",
  "planet": "planète",
  "star": "étoile",
  "galaxy": "galaxie",
  "astronomy": "astronomie",
  "biology": "biologie",
  "chemistry": "chimie",
  "physics": "physique",
  "mathematics": "mathématiques",
  "literature": "littérature",
  "philosophy": "philosophie",
  "religion": "religion",
  "spirituality": "spiritualité",
  "technology": "technologie",
  "innovation": "innovation",
  "discovery": "découverte",
  "environment": "environnement",
  "conservation": "conservation",
  "wildlife": "faune",
  "endangered": "en danger",
  "culture": "culture",
  "tradition": "tradition",
  "custom": "coutume",
  "heritage": "patrimoine",
  "art": "art",
  "painting": "peinture",
  "sculpture": "sculpture",
  "architecture": "architecture",
  "music": "musique",
  "dance": "danse",
  "film": "film",
  "theater": "théâtre",
  "literature": "littérature",
  "poetry": "poésie",
  "fiction": "fiction",
  "friendship": "amitié",
  "love": "amour",
  "hate": "haine",
  "happiness": "bonheur",
  "sadness": "tristesse",
  "anger": "colère",
  "peace": "paix",
  "war": "guerre",
  "freedom": "liberté",
  "democracy": "démocratie",
  "justice": "justice",
  "equality": "égalité",
  "freedom of speech": "liberté d'expression",
  "human rights": "droits de l'homme",
  "environmental protection": "protection de l'environnement",
  "climate change": "changement climatique",
  "technology": "technologie",
  "internet": "internet",
  "social media": "médias sociaux",
  "smartphone": "téléphone intelligent",
  "computer programming": "programmation informatique",
  "science": "science",
  "biology": "biologie",
  "chemistry": "chimie",
  "physics": "physique",
  "mathematics": "mathématiques",
  "education": "éducation",
  "school": "école",
  "teacher": "professeur",
  "student": "étudiant",
  "university": "université",
  "research": "recherche",
  "discovery": "découverte",
  "innovation": "innovation",
  "medicine": "médecine",
  "doctor": "médecin",
  "nurse": "infirmière",
  "patient": "patient",
  "hospital": "hôpital",
  "health": "santé",
  "fitness": "forme physique",
  "nutrition": "nutrition",
  "food": "nourriture",
  "restaurant": "restaurant",
  "chef": "chef cuisinier",
  "menu": "menu",
  "travel": "voyage",
  "adventure": "aventure",
  "tourism": "tourisme",
  "passport": "passeport",
  "ticket": "billet",
  "hotel": "hôtel",
  "reservation": "réservation",
  "language": "langue",
  "translation": "traduction",
  "communication": "communication",
    "act": "agir",
    "attend": "attendre",
    "library": "bibliothèque",
    "sympathy": "compassion",
    "actual": "réel",
    "fabric": "tissu",
    "parent": "parent",
    "pretend": "faire semblant",
    "eventually": "finalement",
    "fabrication": "manufacture",
    "argument": "dispute",
    "embarrassed": "gêné",
    "sympathy": "compassion",
    "location": "emplacement",
    "library": "bibliothèque",
    "private" :"particulier" ,
     "current events":"actualité",
    "achievement":"success",
    "bread":"pain",
    "library": "bibliothèque",
    "prejudice": "préjugé",
"fabricate": "fabriquer",
"institute": "établissement",
"exquisite": "exquis",
"familiar": "connaissant",
"forfeit": "perdre",
"allegiance": "loyauté",
"discern": "discerner",
"incredible": "incroyable",
"melancholy": "mélancolie",
"noxious": "nocif",
"plausible": "plausible",
"restraint": "retenue",
"ultimate": "ultime",
"acquaintance": "connaissance",
"controversy": "controverse",
"courageous": "courageux",
"deceptive": "trompeur",
"feasible": "réalisable",
"inquisitive": "curieux",
"meticulous": "méticuleux",
"obnoxious": "odieux",
"preposterous": "absurde",
"superficial": "superficiel",
"tremendous": "énorme",
"ubiquitous": "omniprésent",
"vicarious": "vicariant",
"cacophony": "cacophonie",
"debilitate": "débilité",
"heterogeneous": "hétérogène",
"insouciant": "insouciant",
"lachrymose": "larmoyant",
"obfuscate": "obfusquer",
"tergiversate": "tergiverser",
"unctuous": "onctueux",
"verisimilitude": "vraisemblance",
"welter": "vouloir",
"xenophobia": "xénophobie",
}

function randomize(tab) {
    var i, j, tmp;
    for (i = tab.length - 1; i > 0; i--) {
        j = Math.floor(Math.random() * (i + 1));
        tmp = tab[i];
        tab[i] = tab[j];
        tab[j] = tmp;
    }
    return tab;}

let zone_question = document.getElementById("question")
let bouton1 = document.getElementById('1')
let bouton2 = document.getElementById('2')
let bouton3 = document.getElementById('3')
let bouton4 = document.getElementById('4')


let scrore = document.getElementById('point')
let point = 0
let nombre = 0
var keys = []
for (const property in mot) {
    keys.push(property)
  }
var values = []
for (const property in mot) {
      values.push(mot[property])
    }

function game(){
    scrore.innerHTML=`${point}/${nombre}`
    var rand = Math.floor(Math.random()*keys.length);

    var mot_de_la_question = keys[rand]
    zone_question.innerHTML = mot_de_la_question


    let run = true
    while(run){
        run = false
        var rep = [
            mot[mot_de_la_question],
            values[Math.floor(Math.random()*keys.length)],
            values[Math.floor(Math.random()*keys.length)],
            values[Math.floor(Math.random()*keys.length)],
        ]
        for(let i in rep){
            for (let j in rep){
                if(rep[i] == rep[j] && i != j){
                    run = true
                }
            }
        }
    }

    rep = randomize(rep)
    bouton1.innerHTML = rep[0]
    bouton2.innerHTML = rep[1]
    bouton3.innerHTML = rep[2]
    bouton4.innerHTML = rep[3]
}
function verif1(){
    let reponse = zone_question.innerHTML
    
    if (bouton1.innerHTML == mot[reponse] ){point++}
    
    nombre++
    game()
}
function verif2(){
    let reponse = zone_question.innerHTML
    if (bouton2.innerHTML == mot[reponse] ){point++}
    
    nombre++
    game()
}
function verif3(){
    let reponse = zone_question.innerHTML
    if (bouton3.innerHTML == mot[reponse] ){point++}
    
    nombre++
    game()
}
function verif4(){
    let reponse = zone_question.innerHTML
    if (bouton4.innerHTML == mot[reponse] ){point++}
    
    nombre++
    game()
}



game()
bouton1.addEventListener("click",verif1)
bouton2.addEventListener("click",verif2)
bouton3.addEventListener("click",verif3)
bouton4.addEventListener("click",verif4)
